import { JsonBlock, PageHeader, Panel, StatCard, StatGrid, StatusBadge } from '../../components/AdminUi.js'
import { formatTimestamp } from '../../lib/format.js'
import type { TimelineSnapshot } from './timeline.schema.js'

export function TimelineView({ snapshot, isRefreshing, refreshFailed }: { snapshot: TimelineSnapshot; isRefreshing: boolean; refreshFailed: boolean }) {
  return <>
    <PageHeader title="行动时间线" description="把 canonical ledger、LLM 调用、工具观测和 token/cache 观测放到同一条只读时间轴；关联强度随标记明确展示。" generatedAt={snapshot.generatedAt} isRefreshing={isRefreshing} refreshFailed={refreshFailed}/>
    <StatGrid><StatCard label="Recent ledger" value={snapshot.summary.ledger}/><StatCard label="LLM calls" value={snapshot.summary.llmCalls} detail={`${snapshot.summary.failedLlmCalls} failed`} tone={snapshot.summary.failedLlmCalls ? 'warn' : 'good'}/><StatCard label="Tool calls" value={snapshot.summary.tools} detail={`${snapshot.summary.failedTools} failed`} tone={snapshot.summary.failedTools ? 'warn' : 'good'}/><StatCard label="Side effects" value={snapshot.summary.sideEffects} tone={snapshot.summary.sideEffects ? 'warn' : 'neutral'}/><StatCard label="Token events" value={snapshot.summary.tokenEvents}/></StatGrid>
    <div className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950">{snapshot.warning}</div>
    <Panel className="mt-4" title="最近 200 个事件" description="按事件时间倒序，不推断跨进程 episode。"><ol className="m-0 list-none p-0">{snapshot.events.map(event => <li key={event.key} className="grid gap-2 border-l-2 border-stone-300 py-3 pl-4 md:grid-cols-[170px_130px_minmax(0,1fr)]"><time className="text-xs text-stone-500">{formatTimestamp(event.at)}</time><div className="flex flex-wrap items-start gap-1"><StatusBadge tone={event.kind === 'tool' || event.kind === 'llm' ? event.ok ? 'good' : 'bad' : event.kind === 'token' ? 'info' : 'neutral'}>{event.kind}</StatusBadge>{event.sideEffect && <StatusBadge tone="warn">side effect</StatusBadge>}</div><div><p className="m-0 text-sm font-semibold">{event.title}</p><p className="mb-0 mt-1 break-all font-mono text-xs leading-5 text-stone-600">{event.detail}</p>{event.jsonDetail && <div className="mt-2"><JsonBlock value={event.jsonDetail} variant="preview" /></div>}<p className="mb-0 mt-1 text-[11px] text-stone-400">{event.correlation}{event.roundIndex === null ? '' : ` · round ${event.roundIndex}`}</p></div></li>)}</ol></Panel>
  </>
}
