import { PageHeader, Panel, StatCard, StatGrid, StatusBadge } from '../../components/AdminUi.js'
import { formatCount, formatDuration, formatPercent } from '../../lib/format.js'
import type { MetricsSnapshot } from './metrics.schema.js'

export function MetricsView({ snapshot, isRefreshing, refreshFailed }: { snapshot: MetricsSnapshot; isRefreshing: boolean; refreshFailed: boolean }) {
  return <>
    <PageHeader title="指标" description="最近 7 天工具调用与 token/cache 观测；这些是运行观测数据，不参与 replay，也不替代 canonical ledger。" generatedAt={snapshot.generatedAt} isRefreshing={isRefreshing} refreshFailed={refreshFailed}/>
    <StatGrid><StatCard label="Tool calls · 7d" value={formatCount(snapshot.totals.toolCalls)} detail={`${snapshot.totals.failedTools} failed`} tone={snapshot.totals.failedTools ? 'warn' : 'good'}/><StatCard label="Side effects" value={formatCount(snapshot.totals.sideEffects)} tone={snapshot.totals.sideEffects ? 'warn' : 'neutral'}/><StatCard label="Input / output" value={`${formatCount(snapshot.totals.inputTokens)} / ${formatCount(snapshot.totals.outputTokens)}`} detail="tokens"/><StatCard label="Cache hit" value={formatPercent(snapshot.totals.cacheHitRate)} detail={`${formatCount(snapshot.totals.cachedTokens)} cached`}/></StatGrid>
    <Panel className="mt-4" title="每日趋势"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-stone-500"><th className="p-2">Day</th><th className="p-2">Tools</th><th className="p-2">Failed</th><th className="p-2">Input</th><th className="p-2">Cached</th><th className="p-2">Output</th></tr></thead><tbody>{snapshot.days.map(day => <tr key={day.day} className="border-b border-stone-100"><td className="p-2 font-medium">{day.day}</td><td className="p-2">{formatCount(day.tools)}</td><td className="p-2">{day.failed}</td><td className="p-2">{formatCount(day.input)}</td><td className="p-2">{formatCount(day.cached)}</td><td className="p-2">{formatCount(day.output)}</td></tr>)}</tbody></table></div></Panel>
    <div className="mt-4 grid gap-4 xl:grid-cols-2">
      <Panel title="工具延迟与失败"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-stone-500"><th className="p-2">Tool</th><th className="p-2">Calls</th><th className="p-2">Fail</th><th className="p-2">P95</th><th className="p-2">Max</th></tr></thead><tbody>{snapshot.tools.map(row => <tr key={row.name} className="border-b border-stone-100"><td className="p-2"><span className="font-medium">{row.name}</span>{row.sideEffects > 0 && <div><StatusBadge tone="warn">{row.sideEffects} side effects</StatusBadge></div>}</td><td className="p-2">{row.calls}</td><td className="p-2">{row.failed}</td><td className="p-2">{formatDuration(row.p95Ms)}</td><td className="p-2">{formatDuration(row.maxMs)}</td></tr>)}</tbody></table></div></Panel>
      <Panel title="LLM operation"><div className="space-y-2">{snapshot.operations.map(row => <div key={row.name} className="rounded-lg bg-stone-100 p-3 text-sm"><div className="flex justify-between gap-3"><strong>{row.name}</strong><span>{row.calls} calls</span></div><p className="mb-0 mt-1 text-xs text-stone-500">{formatCount(row.input)} in · {formatCount(row.cached)} cached · {formatCount(row.output)} out · {formatPercent(row.cacheHitRate)}</p></div>)}</div><h3 className="mt-5 text-sm">Models</h3>{snapshot.models.map(row => <div key={row.name} className="mb-2 flex justify-between gap-3 text-sm"><span>{row.name}</span><span>{formatCount(row.input)} in</span></div>)}</Panel>
    </div>
  </>
}
