import type { ContextSnapshot } from './context.schema.js'

// PROTOTYPE: representative in-memory data for judging the real /context UI via ?demo=1.
export const contextDemoSnapshot = {
  schemaVersion: 6,
  generatedAt: '2026-08-23T10:42:18.000+08:00',
  ledger: {
    total: 129,
    headId: '129',
    checkpointThroughId: '120',
    checkpointUpdatedAt: '2026-08-23T10:30:00.000+08:00',
    typeCounts: [
      { type: 'message', count: 127 },
      { type: 'compaction', count: 2 },
    ],
  },
  runtime: {
    ledgerHeadId: '129',
    updatedAt: '2026-08-23T10:42:18.000+08:00',
  },
  latestUsage: {
    ts: '2026-08-23T10:42:18.000+08:00',
    model: 'gpt-5.6-sol',
    inputTokens: 18_420,
    cachedTokens: 15_890,
    outputTokens: 684,
    cacheHitRate: 0.8626,
  },
  recentLlmCalls: [
    {
      callId: '11111111-1111-4111-8111-111111111111',
      ts: '2026-08-23T10:42:18.000+08:00',
      operation: 'agent.chat',
      actor: 'main_agent',
      provider: 'openai',
      model: 'gpt-5.6-sol',
      status: 'succeeded',
      durationMs: 4_280,
      stopReason: 'stop',
      errorKind: null,
      inputTokens: 18_420,
      cachedTokens: 15_890,
      outputTokens: 684,
      evidence: {
        canonicalRequest: { fingerprint: 'a'.repeat(64), toolNames: ['inbox'] },
        providerRequest: { fingerprint: 'b'.repeat(64), toolNames: ['inbox'] },
        providerResponse: { fingerprint: 'c'.repeat(64), toolNames: ['inbox'] },
        canonicalResponse: { fingerprint: 'd'.repeat(64), toolNames: ['inbox'] },
      },
    },
    {
      callId: '22222222-2222-4222-8222-222222222222',
      ts: '2026-08-23T10:39:06.000+08:00',
      operation: 'agent.chat',
      actor: 'main_agent',
      provider: 'openai',
      model: 'gpt-5.6-sol',
      status: 'succeeded',
      durationMs: 6_940,
      stopReason: 'tool_use',
      errorKind: null,
      inputTokens: 17_736,
      cachedTokens: 14_912,
      outputTokens: 512,
      evidence: {
        canonicalRequest: { fingerprint: 'e'.repeat(64), toolNames: ['memory_search', 'invoke'] },
        providerRequest: { fingerprint: 'f'.repeat(64), toolNames: ['memory_search', 'invoke'] },
        providerResponse: { fingerprint: '0'.repeat(64), toolNames: ['memory_search', 'invoke'] },
        canonicalResponse: { fingerprint: '1'.repeat(64), toolNames: ['memory_search', 'invoke'] },
      },
    },
  ],
  entries: [
    {
      kind: 'compaction',
      id: '120',
      entryType: 'compaction',
      createdAt: '2026-08-23T10:30:00.000+08:00',
      role: null,
      summary: '## 上一阶段摘要\n\n- 已完成 WebAdmin 导航整理。\n- 主 Agent 正在检查 Memory 与会话的近期进展。\n- 后续回答应优先引用 canonical ledger 中的事实。',
      reason: 'token_threshold',
      firstKeptEntryId: '121',
      tokensBefore: 31_840,
      estimatedTokensAfter: 8_460,
      isSplitTurn: false,
      rawPreview: '{"type":"compaction","reason":"token_threshold","firstKeptEntryId":"121"}',
    },
    {
      kind: 'message',
      id: '121',
      entryType: 'message',
      createdAt: '2026-08-23T10:38:52.000+08:00',
      role: 'user',
      summary: '帮我看看 Luna 最近在忙什么，给我一个简短的进展摘要。',
      toolCalls: [],
      thinkingBlocks: [],
      toolCallId: null,
      toolName: null,
      parentEntryId: null,
      result: null,
      rawPreview: '{"role":"user","content":"帮我看看 Luna 最近在忙什么，给我一个简短的进展摘要。"}',
    },
    {
      kind: 'message',
      id: '122',
      entryType: 'message',
      createdAt: '2026-08-23T10:39:01.000+08:00',
      role: 'assistant',
      summary: '',
      toolCalls: [
        {
          id: 'call-memory', name: 'memory_search', displayName: 'memory_search', transportName: null,
          argsPreview: '{\n  "query": "Luna 最近进展",\n  "limit": 5\n}',
          parameters: [{ label: 'query', value: 'Luna 最近进展' }, { label: 'limit', value: '5' }],
        },
        {
          id: 'call-conversations', name: 'invoke', displayName: 'conversation', transportName: 'invoke',
          argsPreview: '{\n  "action": "open",\n  "target": {\n    "kind": "private",\n    "platform": "qq",\n    "accountId": "10000",\n    "externalId": "3999414673"\n  }\n}',
          parameters: [
            { label: 'action', value: 'open' },
            { label: 'target', value: 'QQ 私聊 · 3999414673' },
          ],
        },
      ],
      thinkingBlocks: [],
      toolCallId: null,
      toolName: null,
      parentEntryId: null,
      result: null,
      rawPreview: '{"role":"assistant","tool_calls":["memory_search","invoke"]}',
    },
    {
      kind: 'message',
      id: '123',
      entryType: 'message',
      createdAt: '2026-08-23T10:39:03.000+08:00',
      role: 'tool',
      summary: '找到 3 条相关记忆：WebAdmin 对话视图、媒体描述队列、欧洲行程页面。',
      toolCalls: [],
      thinkingBlocks: [],
      toolCallId: 'call-memory',
      toolName: 'memory_search',
      parentEntryId: '122',
      result: { ok: true, status: 'succeeded', code: null, reason: null },
      rawPreview: '{"ok":true,"matches":3}',
    },
    {
      kind: 'message',
      id: '124',
      entryType: 'message',
      createdAt: '2026-08-23T10:39:05.000+08:00',
      role: 'tool',
      summary: '已打开 QQ 私聊 3999414673，后续 inbox 与 send_message 将使用这个明确 target。',
      toolCalls: [],
      thinkingBlocks: [],
      toolCallId: 'call-conversations',
      toolName: 'invoke',
      parentEntryId: '122',
      result: { ok: true, status: 'succeeded', code: null, reason: null },
      rawPreview: '{"ok":true,"activeTopics":4}',
    },
    {
      kind: 'message',
      id: '125',
      entryType: 'message',
      createdAt: '2026-08-23T10:39:06.000+08:00',
      role: 'assistant',
      summary: '## 最近进展\n\nLuna 目前主要在推进三件事：\n\n1. **WebAdmin 主对话视图**：把 canonical ledger 整理成更像聊天窗口的阅读体验。\n2. **媒体描述队列**：减少重复请求，保持单次尝试和明确失败状态。\n3. **行程内容**：继续整理欧洲行程页面的交通与景点信息。\n\n| 方向 | 状态 | 下一步 |\n| --- | --- | --- |\n| WebAdmin | 进行中 | 验证桌面与手机布局 |\n| 媒体队列 | 已稳定 | 观察真实流量 |\n| 行程页面 | 持续完善 | 补充当天安排 |\n\n> 当前最活跃的是 WebAdmin，对话页面已经进入视觉确认阶段。',
      toolCalls: [],
      thinkingBlocks: [],
      toolCallId: null,
      toolName: null,
      parentEntryId: null,
      result: null,
      rawPreview: '{"role":"assistant","content":"最近进展摘要"}',
    },
    {
      kind: 'message',
      id: '126',
      entryType: 'message',
      createdAt: '2026-08-23T10:41:48.000+08:00',
      role: 'user',
      summary: '那今天最值得优先做什么？',
      toolCalls: [],
      thinkingBlocks: [],
      toolCallId: null,
      toolName: null,
      parentEntryId: null,
      result: null,
      rawPreview: '{"role":"user","content":"那今天最值得优先做什么？"}',
    },
    {
      kind: 'message',
      id: '127',
      entryType: 'message',
      createdAt: '2026-08-23T10:42:11.000+08:00',
      role: 'assistant',
      summary: '',
      toolCalls: [{
        id: 'call-inbox', name: 'inbox', displayName: 'inbox', transportName: null,
        argsPreview: '{\n  "status": "active"\n}', parameters: [{ label: 'status', value: 'active' }],
      }],
      thinkingBlocks: [],
      toolCallId: null,
      toolName: null,
      parentEntryId: null,
      result: null,
      rawPreview: '{"role":"assistant","tool_calls":["inbox"]}',
    },
    {
      kind: 'message',
      id: '128',
      entryType: 'message',
      createdAt: '2026-08-23T10:42:13.000+08:00',
      role: 'tool',
      summary: '检查主 Agent 对话视图的示例数据与响应式验收。',
      toolCalls: [],
      thinkingBlocks: [],
      toolCallId: 'call-inbox',
      toolName: 'inbox',
      parentEntryId: '127',
      result: { ok: true, status: 'succeeded', code: null, reason: null },
      rawPreview: '{"ok":true,"mailboxes":[]}',
    },
    {
      kind: 'message',
      id: '129',
      entryType: 'message',
      createdAt: '2026-08-23T10:42:18.000+08:00',
      role: 'assistant',
      summary: '优先把 **主 Agent 对话视图** 验收完。它已经接近完成，只差确认真实密度下的滚动、工具折叠和 390px 布局；做完就能形成一个完整、可交付的结果。',
      toolCalls: [],
      thinkingBlocks: [],
      toolCallId: null,
      toolName: null,
      parentEntryId: null,
      result: null,
      rawPreview: '{"role":"assistant","content":"优先完成主 Agent 对话视图验收"}',
    },
  ],
  warnings: [],
} satisfies ContextSnapshot
