version: "3"
services:
  napcat:
    container_name: napcat
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    ports:
      - 13000:3000
      - 3001:3001
      - 6099:6099
    network_mode: bridge
    restart: always
    image: mlikiowa/napcat-docker:latest

  redis:
    container_name: my-redis
    image: redis:latest
    ports:
      - "16379:6379"
    environment:
      - REDIS_PASSWORD=c8npecu85kr
    command: redis-server --requirepass c8npecu85kr
    volumes:
      - redis_data:/home/ubuntu/redis-data

volumes:
  redis_data: